apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.toolbox:8200"
      path: "kv-v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-role"