apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-demo-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-secret
  data:
    - secretKey: greeting.message
      remoteRef:
        key: demo
        property: message