---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8-application-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8-application-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8-application-rb
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: k8-application-role
subjects:
  - kind: ServiceAccount
    name: k8-application-sa
---