apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-rds-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rds-secret
  data:
    - secretKey: rds.host
      remoteRef:
        key: rds_service
        property: host

    - secretKey: rds.name
      remoteRef:
        key: rds_service
        property: name

    - secretKey: rds.password
      remoteRef:
        key: rds_service
        property: password

    - secretKey: rds.username
      remoteRef:
        key: rds_service
        property: username